### ISSUE TITLE
Organization 으로 검색이 되는 이슈

### ISSUE THREAD

**Issue by Sn-Kinos** [DirtyBoyz/opgc_frontend#116]
# 버그 리포트
OPGC 버그 리포트 입니다.

## 설명 또는 예시
Organization 인 `kubernetes` 가 검색이 되는 이슈가 발생하고 있습니다.
https://opgc.me/#/users/kubernetes

## 예상 해결 방안
[API](https://github.com/grubersjoe/github-contributions-api) 에서는 [kubernetes](https://github-contributions-api.jogruber.de/v4/kubernetes?y=last) 에 대한 응답으로 아래와 같이 반환되고 있습니다.
```json
{"error":"User 'kubernetes' not found"}
```
프론트에서 일반적인 페이지를 불러오는 것으로 보아 백엔드 쪽 Issue 일지도 모른다는 생각이 들었으나 실수로 Cmd+Enter 를 눌러버리는 바람에 그대로 올리게 되었습니다 😓

**Comment by JAY-Chan9yu** [comment]
@Sn-Kinos 안녕하세요!
OPGC 백엔드 개발자 지찬규라고 합니다!
먼저 관심을 가져주시고 이슈등록해주신 점 너무 감사드립니다!:D

검색시 organization 이 검색되는 이유는 
`https://api.github.com/users/kubernetes` 
와 같은 users api를 사용중인데 url 자체가 users 이기 때문에 org 인지 ,user 인지 구분을 하지 않고 있었습니다!

특별히 문제가 될 것 같지는 않아서 그냥 운영중이 었는데 이번 이슈를 보니까 검색이 안되어야 하는게 맞는것 같네요
OPGC 는 개발자 랭킹 사이트이니!

보니까 위 api에 type이 있어서 요걸로 구분해서 `"type": "User"` 인 경우에만 검색되도록 처리하겠습니다!

### 🤖 포스트맨으로 users api 호출시
![스크린샷 2022-03-07 오후 4 13 20](https://user-images.githubusercontent.com/24591259/156984968-d28fee78-32ce-449a-9140-3f6e89c60ee7.png)

**Comment by Sn-Kinos** [comment]
로그에는 api.github.com 이 아닌 다른 URL이 표시되고 있어서 확인해보려했었는데
다시 보니 프론트에서 콘솔에 뜨는 URL은 잔디 까는 곳에서 쓰이는 URL 이었네요 😮
관련해서 확인해주셔서 감사합니다 xD
